### PR TITLE
check if manually invalidated before removing computation

### PR DESCRIPTION
**Pull request by ecwyne**

### CODE REVIEW

**Comment by stubailo** [comment]
Won't this fix cause us to ignore the Tracker flush cycle and rerun immediately rather than doing it asynchronously?

**Comment by ecwyne** [comment]
@stubailo 
I believe this will now work within the normal Tracker flush cycle and without deleting the computation if it's invalidated because of a `ReactiveMethod.invalidateApply`

**Comment by ecwyne** [comment]
any thoughts @stubailo ?

**Comment by ecwyne** [comment]
@stubailo this continues to be an issue for me in production. Any more thoughts?

**Comment by ecwyne** [comment]
@stubailo ?

**Pull request closed without merging**
